install:
  - choco install gitversion.portable -pre -y
  
before_build:  
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore
  - ps: gitversion /l console /output buildserver

build:
  project: JsonLd.Entities.sln
  
configuration: Release

after_build:
  - .paket\paket.exe pack output nugets include-referenced-projects version %GitVersion_NuGetVersion%
  
after_test:
  - .\packages\OpenCover\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe -targetargs:"src\JsonLD.Entities.Tests\bin\Release\JsonLD.Entities.Tests.dll src\Documentation\bin\Release\JsonLD.Docu.dll" -returntargetcode -filter:"+[JsonLD.Entities]*" -hideskipped:All -output:.\JsonLD.Entities_coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "JsonLD.Entities_coverage.xml"
  
artifacts:
  - path: 'nugets\*.nupkg'

cache:
  - packages -> paket.lock
  
deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true
  - provider: Environment
    name: NuGet
    on:
      branch: master
      appveyor_repo_tag: true